name = "playjonnyapp-com-es"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=playjonnyapp.com.es"
HMAC_KEY = "eb2d30df4f02fcfc147099348ab01b7d2e34e85aa563330c399f8e1d708256d2"
COOKIE_NAME = "u4t"
PLAY_PATH = "try"
BUTTON_ID = "p54e0f0fc0a3ed0120fbab3aa24b8dc30"
GATE_SALT = "856262583be2feb9"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "29no"
CTA_SELECTOR = ".play-button"
